<div class="Flat_mega_menu">

    <i class="fa fa-bars"></i>			<!-- fontawesome mobile button icon -->
    <input class="mobile_button" type="checkbox">		<!-- checkbox button for mobile to expand submenu -->

    <ul>
        <li><a href="#">SM_Mega menu</a></li>
        <li><a href="#">Design</a>
            <ul class="submenu one_col">			<!-- submenu with one column -->
                <li><a href="#">PSD Design</a></li>
                <li><a href="#">Wordpress</a></li>
                <li><a href="#">Magento</a></li>
                <li><a href="#">Joomla</a></li>
                <li><a href="#">E-Commerce<i class="fa fa-angle-right"></i></a>
                    <ul class="submenu one_col">			<!-- submenu with one column -->
                        <li><a href="#">PSD Design</a></li>
                        <li><a href="#">Magento</a></li>
                        <li><i class="fa fa-angle-right"></i><a href="#">Joomla</a>
                            <ul class="submenu one_col">		<!-- submenu with one column -->
                                <li><a href="#">PSD Design</a></li>
                                <li><a href="#">Wordpress</a></li>
                                <li><a href="#">Magento</a></li>
                                <li><a href="#">Joomla</a></li>
                                <li><a href="#">E-Commerce</a></li>
                                <li><a href="#">UI-UX-Design</a></li>
                            </ul>
                        </li>
                        <li><a href="#">E-Commerce</a></li>
                        <li><a href="#">UI-UX-Design</a></li>
                    </ul>
                </li>
                <li><a href="#">UI-UX-Design</a></li>
            </ul>
        </li>
        <li><a href="#">Freebies</a>
            <ul class="submenu two_col">		<!-- submenu with two column -->
                <li><a href="#">PSD Design</a></li>
                <li><a href="#">Wordpress</a></li>
                <li><a href="#">Magento</a></li>
                <li><a href="#">Joomla</a></li>
                <li><a href="#">E-Commerce</a></li>
                <li><a href="#">UI-UX-Design</a></li>
                <li><a href="#">PSD Design</a></li>
                <li><a href="#">Wordpress</a></li>
                <li><a href="#">Magento</a></li>
                <li><a href="#">Joomla</a></li>
                <li><a href="#">E-Commerce</a></li>
                <li><a href="#">UI-UX-Design</a></li>
                <li><a href="#">PSD Design</a></li>
                <li><a href="#">Wordpress</a></li>
                <li><a href="#">Magento</a></li>
                <li><a href="#">Joomla</a></li>
                <li><a href="#">E-Commerce</a></li>
                <li><a href="#">UI-UX-Design</a></li>
            </ul>
        </li>
        <li><a href="#">Tutorial</a>
            <ul class="submenu img_container"> 			<!-- submenu with image container -->
                <li class="title">Latest Tutorials</li>
                <li><img src="img/image_1.png" alt="image 1"><p>Image Description</p></li>
                <li><img src="img/image_1.png" alt="image 1"><p>Image Description</p></li>
                <li><img src="img/image_1.png" alt="image 1"><p>Image Description</p></li>
                <li><img src="img/image_1.png" alt="image 1"><p>Image Description</p></li>
            </ul>
        </li>
        <li><a href="#">News</a>
            <ul class="submenu img_container half">		<!-- submenu with image container half in size + two column-->
                <li class="title">Latest News</li>
                <li><img src="img/image_1.png" alt="image 1"><p>Image Description</p></li>
                <li><img src="img/image_1.png" alt="image 1"><p>Image Description</p></li>
                <li><img src="img/image_1.png" alt="image 1"><p>Image Description</p></li>
                <li><img src="img/image_1.png" alt="image 1"><p>Image Description</p></li>

                <div class="two_col">
                    <li class="title">Category One</li>
                    <li class="title">Category Two</li>


                    <li><a href="#">PSD Design</a></li>
                    <li><a href="#">Wordpress</a></li>
                    <li><a href="#">Magento</a></li>
                    <li><a href="#">Joomla</a></li>
                    <li><a href="#">PSD Design</a></li>
                    <li><a href="#">Wordpress</a></li>
                    <li><a href="#">Magento</a></li>
                    <li><a href="#">Joomla</a></li>
                    <li><a href="#">PSD Design</a></li>
                    <li><a href="#">Wordpress</a></li>
                    <li><a href="#">Magento</a></li>
                    <li><a href="#">Joomla</a></li>
                    <li><a href="#">PSD Design</a></li>
                    <li><a href="#">Wordpress</a></li>
                    <li><a href="#">Magento</a></li>
                    <li><a href="#">Joomla</a></li>
                </div>
            </ul>
        </li>
        <li><a href="#">More</a>
            <ul class="submenu four_col"> <!-- submenu with four column -->
                <li class="title">Category One</li>
                <li class="title">Category Two</li>
                <li class="title">Category Three</li>
                <li class="title">Category Four</li>

                <li><a href="#">PSD Design</a></li>
                <li><a href="#">Wordpress</a></li>
                <li><a href="#">Magento</a></li>
                <li><a href="#">Joomla</a></li>
                <li><a href="#">E-Commerce</a></li>
                <li><a href="#">UI-UX-Design</a></li>
                <li><a href="#">PSD Design</a></li>
                <li><a href="#">Wordpress</a></li>
                <li><a href="#">Magento</a></li>
                <li><a href="#">Joomla</a></li>
                <li><a href="#">E-Commerce</a></li>
                <li><a href="#">UI-UX-Design</a></li>
                <li><a href="#">PSD Design</a></li>
                <li><a href="#">Wordpress</a></li>
                <li><a href="#">Magento</a></li>
                <li><a href="#">Joomla</a></li>
                <li><a href="#">E-Commerce</a></li>
                <li><a href="#">UI-UX-Design</a></li>
                <li><a href="#">PSD Design</a></li>
                <li><a href="#">Wordpress</a></li>
                <li><a href="#">Magento</a></li>
                <li><a href="#">Joomla</a></li>
                <li><a href="#">E-Commerce</a></li>
                <li><a href="#">UI-UX-Design</a></li>
            </ul>
        </li>
        <li class="social_bar"><a href="#">Follow us</a>	<!-- social bar -->
            <ul>
                <li><i class="fa fa-twitter"></i><a href="#">Twitter</a></li>
                <li><i class="fa fa-rss"></i><a href="#">RSS</a></li>
                <li><i class="fa fa-facebook"></i><a href="#">Facebook</a></li>
                <li><i class="fa fa-pinterest"></i><a href="#">Pinterest</a></li>
                <li><i class="fa fa-google-plus"></i><a href="#">Google</a></li>
                <li><i class="fa fa-skype"></i><a href="#">Skype</a></li>
                <li><i class="fa fa-linkedin"></i><a href="#">Linkedin</a></li>
                <li><i class="fa fa-flickr"></i><a href="#">Flickr</a></li>
            </ul>
        </li>

    </ul>
</div>